#!/usr/bin/env python
"""bakeoff_gen.py — generate the harness-bakeoff flow from lockstep.toml (D4).

    python contrib/bakeoff_gen.py                       # -> flows/factory/harness-bakeoff.generated.tg.json
    python contrib/bakeoff_gen.py --config lockstep.toml --tasks my-tasks.json --out -

Executor binding is per-node, so a stanza-per-item map is not expressible in
the taskgraph format — this flow is GENERATED instead: one readonly work node
per (stanza x canned task), then a single judge over all results emitting
ScoreCard[]. `doctor` catches FLAG drift after a harness upgrade; this catches
QUALITY drift. Run it beside doctor after upgrades. It spends real tokens and
the generated flow's description says so.

--tasks: a JSON array of prompt strings; the default set is three cheap,
repo-agnostic probes. Nodes are readonly only on stanzas that declare
readonly_argv (§6.11 would reject the rest).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

DEFAULT_TASKS = [
    "Read README.md in this repository and reply with exactly one sentence stating "
    "what the repository is. No preamble.",
    'Reply with ONLY this JSON object, computed: {"answer": <the sum of 17 and 25>}',
    "List the file names (names only, one per line) at the repository root. "
    "Do not describe them.",
]


def generate(config_path: Path, tasks: list[str]) -> dict:
    data = tomllib.loads(config_path.read_text(encoding="utf-8"))
    executors: dict = data.get("executors", {})
    if not executors:
        raise SystemExit(f"no [executors.*] stanzas in {config_path}")
    nodes = []
    run_ids: list[str] = []
    seen_ids: set[str] = set()
    for stanza_name, stanza in sorted(executors.items()):
        readonly = bool(stanza.get("readonly_argv"))
        # §6-legal id: lowercase, [a-z0-9-] only — and DEDUPED, since legal
        # stanza names ("My_Agent" vs "my-agent") can collapse to one slug.
        slug = re.sub(r"-+", "-", re.sub(r"[^a-z0-9-]", "-", stanza_name.lower())).strip("-")
        slug = slug or "stanza"
        base, n = slug, 2
        while slug in seen_ids:
            slug, n = f"{base}-{n}", n + 1
        seen_ids.add(slug)
        for i, task in enumerate(tasks, start=1):
            node_id = f"run-{slug}-t{i}"
            run_ids.append(node_id)
            spec = {"task": task, "executor": stanza_name}
            if readonly:
                spec["readonly"] = True
            nodes.append({
                "id": node_id,
                "role": "work",
                "kind": "harness",
                "spec": spec,
                "output": "text",
                "timeout_s": 300,
            })
    judge_lines = [
        "You are judging harness output quality after an upgrade. For each numbered "
        "result below, score 0-10: did it follow the instruction exactly (format, "
        "brevity, correctness)? The tasks and results follow as data.",
        "",
    ]
    for node_id in run_ids:
        judge_lines.append(f"[{node_id}]:")
        judge_lines.append(f"{{steps.{node_id}.output}}")
        judge_lines.append("")
    judge_lines.append(
        "Your result MUST be ONLY a JSON array of ScoreCard objects, one per result: "
        'stanza (the part of the node id between "run-" and "-t"), task (the node id), '
        "score (0-10 integer), rationale (one sentence)."
    )
    nodes.append({
        "id": "judge",
        "role": "work",
        "kind": "harness",
        "depends_on": run_ids,
        "spec": {"task": "\n".join(judge_lines)},
        "output": "json",
        "contract": "ScoreCard[]",
        "timeout_s": 900,
        "final": True,
    })
    return {
        "format_version": "1.0",
        "name": "harness-bakeoff",
        "description": (
            "GENERATED by contrib/bakeoff_gen.py from lockstep.toml — regenerate after "
            "editing stanzas. Quality drift check (D4): one readonly probe per "
            "(stanza x canned task), one judge emitting ScoreCard[]. SPENDS real tokens "
            f"({len(run_ids)} probes + 1 judge). doctor catches flag drift; this catches "
            "quality drift — run both after any harness upgrade."
        ),
        "contracts_module": "flows/factory_contracts.py",
        "budget": {
            "max_agent_spawns": len(run_ids) + 3,
            "max_run_minutes": 60,
        },
        "nodes": nodes,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", default="lockstep.toml")
    ap.add_argument("--tasks", default=None, help="JSON array of prompt strings")
    ap.add_argument("--out", default="flows/factory/harness-bakeoff.generated.tg.json",
                    help='"-" prints to stdout')
    ns = ap.parse_args(argv)
    tasks = DEFAULT_TASKS
    if ns.tasks:
        tasks = json.loads(Path(ns.tasks).read_text(encoding="utf-8"))
        if not isinstance(tasks, list) or not all(isinstance(t, str) for t in tasks):
            raise SystemExit("--tasks must be a JSON array of strings")
    flow = generate(Path(ns.config), tasks)
    text = json.dumps(flow, indent=2, ensure_ascii=False) + "\n"
    if ns.out == "-":
        print(text, end="")
    else:
        out = Path(ns.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"wrote {ns.out} — check it with: lockstep verify {ns.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
