"""Generate mission-ux.html — the design target for mission-ux-work-order.md.

Authored data, generated assembly: the base CSS is imported from the SHIPPED
renderer (contrib/mission_server.stylesheet(), cost slots substituted exactly
as the page does) so the mockup cannot drift from the page's real chrome; only
the block under MOCKUP ADDITIONS is new, and it is what the work order's three
batches would add. Run from the repo root:

    .venv\\Scripts\\python.exe docs\\proposals\\mockups\\make-mission-ux.py

Static output, no server, no fetch. Same authority rule as trace-page.html:
where this file and the shipped page disagree, the shipped page is right.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "contrib"))
import mission_server as ms  # noqa: E402

HEADER = """<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MISSION — mockup (mission-ux-work-order.md)</title>
<!--
  DESIGN TARGET, 2026-09-11, for docs/proposals/mission-ux-work-order.md.
  MOCKUP ONLY. Static fake data, no server, no fetch — not shipping code.
  Generated by make-mission-ux.py beside this file; edit THAT, not this.

  Base CSS is contrib/mission_server.py stylesheet() imported at build time
  (cost slots substituted from COST_HEX, exactly as the page does); everything
  below the "MOCKUP ADDITIONS" marker is new and is what the work order's
  three batches would add. Where this file and the shipped page disagree,
  the shipped page is right — same rule as trace-page.html.

  What is new here, by batch:
    B0  the blocker card (.blocked) — the failure case above the fold,
        decision card first, blocker second
    B1  the meter lives inside the "agent tasks" tile; ONE cost disclosure
        with a history/kept-only switch (both bodies render; JS-off shows
        both, the l0/l1 fallback pattern)
    B2  the peek panel (.peek, an <aside> OUTSIDE .wrap) open on the failed
        step; the drawers card in its ABOVE-THRESHOLD form (named absence,
        never blank)

  This static render shows board AND timeline at once — the no-JS fallback,
  same as trace-page-shipped-timeline.png.

  Palette: unchanged from shipped, re-validated 2026-09-11:
    validate_palette.js "#3987e5,#d95926,#199e70,#c98500"
        - -mode dark - -surface "#141517"   -> ALL CHECKS PASS
    (worst adjacent CVD dE 8.4 protan — legal, the stack has 2px gaps and a
    value-labelled legend; normal-vision 19.8; all >= 3:1 on the surface)
  The blocker card takes - -critical: a reserved STATUS step with its icon
  and its glossary word, never a categorical hue as chrome. TWO shipped
  tokens (- -raise, - -accent) are used at mission_server.py:813/830/836 but
  defined nowhere — the rail highlight and the critical-path edge render as
  nothing on the shipped page. Defined here as the B0 repair (F7 in the
  work order), not silently reproduced.
  (Double hyphens are split in this comment because HTML forbids them here.)
-->
"""

ADDITIONS = """
/* ===================== MOCKUP ADDITIONS (the work order) ===================== */
:root{--raise:#191b1e;--accent:var(--ink)}
/* ^ B0 repairs (work-order F7): BOTH tokens are used by the shipped sheet and
   defined nowhere — the rail highlight and the critical-path edge/swatch
   silently paint nothing. --accent is ink: the critical path is chrome. */
.mock-note{max-width:1760px;margin:0 auto 18px;border:1px dashed var(--line);
 border-radius:8px;padding:9px 14px;color:var(--muted);font-size:12px}
.mock-note b{color:var(--ink-2);font-weight:600}
/* B0 - the blocker card: same grammar as .decide, critical status step */
.blocked{border-left:2px solid var(--critical)}
.blocked h2{color:var(--critical);font-size:12.5px}
.blocked .fact{color:var(--muted);font-size:12.5px;margin:8px 0 0}
.blocked .fact a{color:var(--ink-2)}   /* chrome is ink — never UA blue */
/* B2 - while the panel is open on a wide screen the page REFLOWS instead of
   being covered: nothing readable may sit underneath it. (Datadog overlays;
   this page must not — hidden content on an honesty-first board reads as
   missing content.) Below 900px the panel stacks instead. */
body.peek-open{padding-right:492px}
@media (max-width:900px){body.peek-open{padding-right:20px}}
/* B1 - the meter inside the agent-tasks tile */
.tile .track{margin-top:8px}
.tile .consent{color:var(--muted);font-size:11px;margin-top:7px;line-height:1.45}
/* B1 - the switch inside the one cost disclosure */
.cost-modes{display:flex;gap:4px;margin:8px 0 8px}
/* B2 - the peek panel: an <aside> OUTSIDE .wrap, so a poll swap never kills it */
.peek{position:fixed;top:0;right:0;bottom:0;width:min(460px,92vw);z-index:9;
 background:var(--surface);border-left:1px solid var(--line);
 box-shadow:-28px 0 56px rgba(0,0,0,.5);padding:16px 18px 20px;overflow:auto}
.peek-head{display:flex;align-items:center;gap:9px;margin-bottom:10px}
.peek-head .ico{font-size:13px}
.peek-head h2{font-size:13px;font-weight:600;color:var(--ink);margin:0;flex:1}
.peek-head .word{color:var(--muted);font-size:12px}
.peek-foot{color:var(--muted);font-size:11.5px;margin-top:12px}
.peek pre{margin-bottom:10px}
@media (max-width:900px){.peek{position:static;width:auto;border-left:0;
 border-top:1px solid var(--line);box-shadow:none}}
/* B2 - the drawers card above DRAWER_INLINE_MAX: a named absence */
.inline-limit{color:var(--muted);font-size:12.5px;margin:0 0 10px}
"""


def seg(cls, left, width, tip=""):
    t = f'<span class="tip">{tip}</span>' if tip else ""
    return (f'<span class="seg {cls}" tabindex="0" '
            f'style="left:{left}%;width:{width}%">{t}</span>')


def wfrow(icon, icls, name, word, track, crit=False):
    return (f'<div class="wf-row{" crit" if crit else ""}">'
            f'<div class="wf-lab"><span class="n"><span class="ico {icls}">{icon}</span>'
            f'<a href="#step-verify-batch-07">{name}</a></span>'
            f'<span class="w">{word}</span></div>'
            f'<div class="wf-track">{track}</div></div>')


ROWS = "\n".join([
    wfrow("&#10003;", "good", "collect targets", "done", seg("good", 0, 2.0, "9s"), crit=True),
    wfrow("&#10003;", "good", "plan the batches", "done", seg("good", 2.4, 3.2, "2m01s"), crit=True),
    wfrow("&#10003;", "good", "rewrite batch 01", "done", seg("good", 6.2, 15.4, "9m52s")),
    wfrow("&#10003;", "good", "rewrite batch 02", "done", seg("good", 6.2, 18.0, "11m31s")),
    wfrow("&#10003;", "good", "rewrite batch 07", "done (sent back once)",
          seg("ser", 6.2, 13.6) + seg("good", 21.4, 16.2, "10m22s"), crit=True),
    wfrow("&#10003;", "good", "verify batch 01", "done", seg("good", 22.0, 2.2, "1m24s")),
    wfrow("&#10007;", "crit", "verify batch 07", "stopped with a problem",
          seg("crit", 38.4, 2.6, "3 tries"), crit=True),
    wfrow("&#10003;", "good", "render the evidence", "done", seg("good", 42.0, 1.6, "58s")),
    wfrow("&#9684;", "warn", "apply the codemod", "needs you", ""),
])
GRID = "".join(f'<div class="gridline" style="left:{p}%"></div>'
               for p in (15.6, 31.2, 46.9, 62.5, 78.1, 93.7))
TICKS = "".join(f'<div class="tick" style="left:{p}%">{t}</div>'
                for p, t in ((0, "09:31"), (15.6, "09:41"), (31.2, "09:51"),
                             (46.9, "10:01"), (62.5, "10:11"), (78.1, "10:21"),
                             (93.7, "10:31")))

BODY = f"""<body class="peek-open" data-run-token="mockup" data-event-cursor="0" data-run="codemod-apply-20260911T093012Z">
<p class="mock-note"><b>MOCKUP</b> &mdash; the target state for
docs/proposals/mission-ux-work-order.md. Static render, both views visible
(the no-JS fallback). New against the shipped page: the blocker card (B0),
the meter inside its tile and one cost disclosure (B1), the peek panel and
the above-threshold drawers card (B2).</p>
<div class="shell">
<nav class="side"><div class="side-h">runs on this machine</div>
<a class="side-run cur" href="#"><span class="dot crit"></span><span class="side-name">codemod-apply</span><span class="side-word">09:31 &middot; stopped with a problem</span></a>
<a class="side-run" href="#"><span class="dot good"></span><span class="side-name">codemod-propose</span><span class="side-word">08:02 &middot; done</span></a>
<a class="side-run" href="#"><span class="dot warn"></span><span class="side-name">triage-intake</span><span class="side-word">07:44 &middot; needs you</span></a>
<a class="side-run" href="#"><span class="dot good"></span><span class="side-name">status-digest</span><span class="side-word">07:00 &middot; done</span></a>
<a class="side-run" href="#"><span class="dot good"></span><span class="side-name">selftest-replay</span><span class="side-word">06:12 &middot; done</span></a>
<div class="side-empty">31 older, not listed</div>
</nav>
<div class="wrap">
<div class="top"><span class="brand">MISSION</span>
<span class="runid">codemod-apply-20260911T093012Z</span><span class="spacer"></span>
<span class="chip"><span class="dot mut"></span>not running</span>
<span class="chip"><span class="dot good"></span>record verified &middot; 212 events</span></div>

<p class="hero">step 58 of 64&nbsp; -&nbsp; stopped with a problem&nbsp; -&nbsp; 1 h 4 m&nbsp; -&nbsp; your decision is next</p>
<p class="hero-sub">This page only reads files. Decisions are not made here &mdash;
when something needs you, it happens in the terminal.</p>

<div class="card decide"><h2>&#8855; needs you &mdash; a decision</h2>
<div class="evidence">codemod: rename Customer.balance &rarr; Customer.available_balance
proposed by  : rewrite batches 01&ndash;06 (312 call sites, 41 files)
verify gates : batches 01&ndash;06 pass; batch 07 is stopped and is NOT in this apply
tests        : 2,114 passed, 0 failed

blast radius : 41 files, all under src/billing/ &mdash; nothing outside it
reversible   : yes &mdash; one revert commit restores the tree</div>
<p class="terminal-note">{ms.TERMINAL_SENTENCE}</p></div>

<div class="card blocked"><h2>&#10007; stopped with a problem &mdash; verify batch 07</h2>
<div class="evidence">contract violation: output failed the Verdict contract (exit 3)</div>
<p class="fact">3 attempts &middot; 3 steps cannot start until this is fixed &middot;
<a class="name" href="#step-verify-batch-07">what happened at this step</a></p></div>

<div class="stats">
<div class="tile"><div class="k">step</div><div class="v">58 of 64</div></div>
<div class="tile"><div class="k">node time</div><div class="v">3h 41m</div></div>
<div class="tile"><div class="k">agent tasks used</div><div class="v">14 of 25</div>
<div class="track"><div class="fill" style="width:56%"></div><div class="ceil"></div></div>
<div class="consent">The ceiling is the number this flow declared &mdash; the one you agreed to before anything started.</div></div>
<div class="tile"><div class="k">your decision</div><div class="v">next</div></div>
</div>

<div class="card"><h2>spend</h2><pre>2 rework rounds | 3h41m of node time
tokens in 2.1 M &middot; out 148 K &middot; cache read 9.4 M &middot; cache write 612 K
running: nothing - a decision waits and a step has stopped
this session: orchestrator transcript 3.2 M in / 41 K out</pre></div>

<div class="card"><div class="cardhead"><h2>the steps</h2>
<div class="viewswitch">
<button class="btn" data-view="l0" aria-pressed="true">board</button>
<button class="btn" data-view="l1" aria-pressed="false">show every step</button>
</div></div>
<div id="l0" class="steps">
<div class="step"><span class="ico crit">&#10007;</span><a class="name" href="#step-verify-batch-07">verify batch 07</a><span class="word">stopped with a problem</span></div>
<div class="note">contract violation: output failed the Verdict contract (exit 3)</div>
<div class="step"><span class="ico warn">&#9684;</span><a class="name" href="#step-apply">apply the codemod</a><span class="word">needs you</span></div>
<div class="step"><span class="ico mut">&#9675;</span><a class="name" href="#step-vb7r">re-verify batch 07</a><span class="word">waiting</span></div>
<div class="step"><span class="ico mut">&#9675;</span><a class="name" href="#step-merge">fold batch 07 into the apply</a><span class="word">waiting</span></div>
<div class="tail">52 finished&nbsp; &middot; &nbsp;8 not started</div>
</div>
<div id="l1">
<div class="wf-legend">
<span><i class="k-crit"></i>the chain everything else waited for</span>
<span><i class="k-roll"></i>work sent back and files restored</span>
<span><i class="k-ser"></i>an attempt that was replaced</span></div>
<div class="wf-plot">
<div class="wf-scale">{GRID}<div class="rollback" style="left:21.4%"></div></div>
<div class="wf">
{ROWS}
</div>
<div class="wf-axis">{TICKS}</div>
</div>
<p class="inline-limit">&hellip; 55 more steps &mdash; every value above is also in the table twin.</p>
<details open><summary>the same thing as a table</summary><table>
<tr><th>step</th><th>state</th><th>started</th><th class="n">worked for</th><th class="n">tries</th></tr>
<tr><td>rewrite batch 07</td><td>done (sent back once)</td><td>09:35</td><td class="n">19m58s</td><td class="n">2</td></tr>
<tr><td>verify batch 07</td><td>stopped with a problem</td><td>09:58</td><td class="n">4m32s</td><td class="n">3</td></tr>
<tr><td>render the evidence</td><td>done</td><td>10:14</td><td class="n">58s</td><td class="n">1</td></tr>
<tr><td>apply the codemod</td><td>needs you</td><td>&mdash;</td><td class="n">&mdash;</td><td class="n">&mdash;</td></tr>
</table></details>
</div></div>

<div class="card"><h2>what it has cost</h2>
<div class="stack">
<i style="background:var(--c1);width:41%" title="input 2,104,331"></i>
<i style="background:var(--c2);width:9%" title="output 148,220"></i>
<i style="background:var(--c3);width:44%" title="cache read 9,401,556"></i>
<i style="background:var(--c4);width:6%" title="cache write 612,004"></i></div>
<div class="legend">
<span><i class="sw" style="background:var(--c1)"></i>input 2,104,331</span>
<span><i class="sw" style="background:var(--c2)"></i>output 148,220</span>
<span><i class="sw" style="background:var(--c3)"></i>cache read 9,401,556</span>
<span><i class="sw" style="background:var(--c4)"></i>cache write 612,004</span></div>
<details id="cost-tree" open><summary>per step</summary>
<div class="cost-modes viewswitch">
<button class="btn" aria-pressed="true">every attempt</button>
<button class="btn" aria-pressed="false">kept only</button></div>
<pre>&#10003; codemod-apply    58/64 &middot; 3h41m &middot; $4.87
(history: every attempt is counted)
&#10003; collect targets   shell    2s
&#10003; plan the batches  harness  2m01s  $0.11
&#9484; &#10003; rewrite batch 01  harness  9m52s  $0.63
&#9492; &#10003; rewrite batch 02  harness  11m31s $0.71
&#10003; rewrite batch 07  harness  &#8635;1  19m58s  $1.35
   attempt 1  (superseded)
   kept
&#10007; verify batch 07   shell    3 tries  4m32s
&#10003; render evidence   shell    58s</pre></details></div>

<div class="card"><h2>ACTIVITY</h2><pre>nothing is spending - a step has stopped and a decision waits in the terminal</pre></div>

<div class="card"><h2>what just happened</h2><div class="feed">
<div>10:02&nbsp; verify batch 07&nbsp; failed &mdash; attempt 3 of 3</div>
<div>10:13&nbsp; render the evidence&nbsp; running</div>
<div>10:14&nbsp; render the evidence&nbsp; done</div>
<div>10:14&nbsp; apply the codemod&nbsp; needs you</div>
</div></div>

<div class="card"><h2>what happened at each step</h2>
<p class="inline-limit">This run is above the inline limit (64 steps). A step
opens in the panel on this page; from a terminal,
<code>lockstep status runs\\codemod-apply-20260911T093012Z</code> shows the
same detail.</p>
<details id="step-verify-batch-07" open><summary>verify batch 07 &mdash; stopped with a problem</summary>
<pre>The full detail is on this page&rsquo;s panel (open now, to the right), or from
a terminal: lockstep status runs\\codemod-apply-20260911T093012Z</pre></details>
<details id="step-apply"><summary>apply the codemod &mdash; needs you</summary></details>
<details id="step-rb07"><summary>rewrite batch 07 &mdash; done (sent back once)</summary></details>
</div>

<p class="foot">This page only reads files. It never changes the run.</p>
</div></div>

<aside class="peek" aria-label="step detail">
<div class="peek-head"><span class="ico crit">&#10007;</span>
<h2>verify batch 07</h2><span class="word">stopped with a problem</span>
<button class="btn" aria-label="close">&times;</button></div>
<pre>state      : failed
attempts   : 3
error      : contract violation: output failed the
             Verdict contract (exit 3)
started_at : 2026-09-11T09:58:12Z
ended_at   : 2026-09-11T10:02:44Z

agent
asked for  : claude-code | claude-sonnet-5
tools      : read-only set (Bash denied)
tool calls : 41
tokens     : 118,204 in &middot; 3,911 out
cost       : $0.42

artifacts
prompt.txt                      4,112 bytes
result-attempt1.json            1,893 bytes
result-attempt2.json            1,721 bytes
result.json                     1,684 bytes
stdout.log                     48,220 bytes</pre>
<table>
<tr><th>term</th><th>what it means</th><th>value</th></tr>
<tr><td>step id</td><td>the name the system uses for this step</td><td>verify-batch-07</td></tr>
<tr><td>input-hash parts</td><td>the things this step was given &mdash; if any of them changes, the step is done again rather than reused</td><td>argv, config, prompt.reads_manifest</td></tr>
<tr><td>what moved</td><td>which of those things changed last time, and so why this step could not be reused</td><td>prompt.reads_manifest</td></tr>
<tr><td>record head</td><td>a fingerprint of this run's whole history; it changes if anything in that history is altered</td><td>8c4e21aa90d31f77</td></tr>
<tr><td>record check</td><td>whether that history still adds up when it is recomputed, just now</td><td>212 events verified</td></tr>
</table>
<p class="peek-foot">Esc closes. This is the same detail the step's drawer
carries &mdash; one renderer, two places.</p>
</aside>
"""


def main() -> int:
    html = HEADER + "<style>" + ms.stylesheet() + ADDITIONS + "</style>\n" + BODY
    assert "D:\\Shared" not in html and "Ali Sucipto" not in html, "local path leaked"
    out = Path(__file__).with_name("mission-ux.html")
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(html):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
